server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: PAYMENT-SERVICE
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.cloud.entities
